#!/usr/bin/env node
/**
 * Turns a binary asset (a Blender/Meshy .glb, a generated .png/.mp3, ...)
 * into an ES module that base64-embeds it, so it ships inside the JS bundle
 * instead of as a separate file.
 *
 * Why base64-in-JS and not a plain file: the built game must run offline
 * from `file://` with zero network (web/ARCHITECTURE.md rule 3). Chrome
 * blocks fetch()/XHR from a file:// page to another file:// resource, so a
 * separate .glb next to index.html loads fine under `npm run dev` (an HTTP
 * origin) and silently fails once someone double-clicks dist/index.html.
 * A base64 string literal has no such restriction — it's already in memory
 * when the page loads.
 *
 * Usage:
 *   node tools/embed-asset.mjs <input-file> [--out <path>] [--name <ident>]
 *
 * Default --out: <input-file> with its extension replaced by .embed.js.
 * Default --name: the input's basename, camelCased.
 *
 * The generated module exports { data, mime, bytes } — see
 * web/src/render/assets/loadModel.js for how a game consumes it.
 */
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

const MIME = {
  '.glb': 'model/gltf-binary',
  '.gltf': 'model/gltf+json',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.mp3': 'audio/mpeg',
  '.ogg': 'audio/ogg',
  '.wav': 'audio/wav',
};

// Warn, don't fail: a bundle-bloat budget is a judgment call for the
// integrator, not something this script should silently enforce.
const WARN_BYTES = 2 * 1024 * 1024;

function toIdent(base) {
  return base
    .replace(/\.[^.]+$/, '')
    .replace(/[^a-zA-Z0-9]+(.)/g, (_, c) => c.toUpperCase())
    .replace(/^[^a-zA-Z_]/, '_$&');
}

async function main() {
  const args = process.argv.slice(2);
  const input = args[0];
  if (!input || input.startsWith('--')) {
    console.error('usage: node tools/embed-asset.mjs <input-file> [--out <path>] [--name <ident>]');
    process.exit(1);
  }

  const outIdx = args.indexOf('--out');
  const nameIdx = args.indexOf('--name');
  const ext = path.extname(input).toLowerCase();
  const out = outIdx !== -1 ? args[outIdx + 1] : input.replace(/\.[^.]+$/, '.embed.js');
  const name = nameIdx !== -1 ? args[nameIdx + 1] : toIdent(path.basename(input));
  const mime = MIME[ext] || 'application/octet-stream';

  const buf = await readFile(input);
  const base64 = buf.toString('base64');

  if (buf.byteLength > WARN_BYTES) {
    console.warn(
      `[embed-asset] ${input} is ${(buf.byteLength / 1024 / 1024).toFixed(2)}MB raw ` +
      `(~${((buf.byteLength * 4 / 3) / 1024 / 1024).toFixed(2)}MB as base64 in the bundle). ` +
      `Decimate/compress in Blender before embedding, or confirm this is intentional.`
    );
  }

  const module = `// Generated by tools/embed-asset.mjs from ${path.relative(process.cwd(), input)}
// Do not hand-edit — re-run the script if the source asset changes.
export const ${name}Mime = ${JSON.stringify(mime)};
export const ${name}Bytes = ${buf.byteLength};
export const ${name}Data = ${JSON.stringify(base64)};
`;

  await writeFile(out, module);
  console.log(`[embed-asset] wrote ${out} (${name}Data, ${mime}, ${buf.byteLength} bytes raw)`);
}

main();
